version: "3.8"
services:
  mysql:
    container_name: MasterTicketDB
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=master_ticket
      - MYSQL_USER=sgs1159
      - MYSQL_PASSWORD=vace1159~
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul